[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "FastBNNs"
license = "BSD-3-Clause"
license-files = ["LICENSE.md"]
description = "Fast training and inference for Bayesian neural networks."
readme = "README.md"