[project]
name = "fastbnns"
description = "Fast training and inference for Bayesian neural networks."
dynamic = ["version"]
authors = [
  { name="David J. Schodt", email="dschodt@lanl.gov" },
]
license = "BSD-3-Clause"
license-files = ["LICENSE.md"]
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "scipy",
]

[project.optional-dependencies]
plot = ["matplotlib"]
examples = ["scipy"]

[project.urls]
Homepage = "https://github.com/lanl/FastBNNs"
Repository = "https://github.com/lanl/FastBNNs"
Issues = "https://github.com/lanl/FastBNNs/issues"

[build-system]
requires = ["setuptools >= 77.0.3", "setuptools-git-versioning >= 2.1.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools-git-versioning]
enabled = true
template = "{tag}"
dirty_template = "{tag}.post{ccount}"
